version: '3.3'

volumes:
  media: {}

services:
  # RethinkDB
  rethink:
    image: rethinkdb:2.3
    restart: always
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    command: ["rethinkdb", "--initial-password", "${RDB_PASSWORD}", "--bind", "all"]

  # Redis
  redis:
    restart: always
    image: sameersbn/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/var/lib/redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  # Application
  web:
    image: smpa:latest
    environment:
      - SERVER_ENV=development
      - ENVKEY=${ENVKEY}
      - INDOCKER=1
    restart: always
    build:
      context: ./web
      args:
        - SERVER_ENV=development
        - ENVKEY=${ENVKEY}
    volumes:
      - ./web/smpa/:/usr/srv/app:Z
    ports:
      - "8000:8000"
      - "5000:5000"
    links:
      - rethink
      - redis
    depends_on:
      - rethink
      - redis

    command: sleep 1000000
