version: '3.3'

volumes:
  media: {}
  localstack-data: {}

services:

  # S3
  localstack-s3:
    image: localstack/localstack:latest
    container_name: localstack-s3
    environment:
     - SERVICES=s3:5002
     - DEFAULT_REGION=eu-west-2
     - DATA_DIR=/tmp/localstack/data
    ports:
     - "5002:5002"
     - "9999:8080"
    volumes:
      - ./docker/localstack-data:/tmp/localstack

  # RethinkDB
  rethink:
    image: rethinkdb:2.3
    restart: always
    ports:
      - "8080:8080"
      - "28015:28015"
      - "29015:29015"
    command: ["rethinkdb", "--initial-password", "${RDB_PASSWORD}", "--bind", "all"]

  # Redis
  redis:
    restart: always
    image: sameersbn/redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./docker/redis:/var/lib/redis
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  # Application
  web:
    image: smpa:latest
    environment:
      - SERVER_ENV=development
      - ENVKEY=${ENVKEY}
      - INDOCKER=1
      # Service fails if we don't do this, see: https://github.com/localstack/localstack/issues/528
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_DEFAULT_REGION=eu-west-2
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    restart: always
    build:
      context: ./app
      dockerfile: ../docker/web/Dockerfile
      args:
        - SERVER_ENV=development
        - ENVKEY=${ENVKEY}
    volumes:
      - ./app:/usr/srv/app:Z
    ports:
      - "8000:8000"
      - "5000:5000"
    links:
      - rethink
      - redis
    depends_on:
      - rethink
      - redis

    command: sleep 1000000
