ZSH=$HOME/.oh-my-zsh

ZSH_THEME="hactar"

plugins=(zsh-256color git autojump fabric pip python wd zsh-autosuggestions)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

alias runserver="python manage.py runserver 0.0.0.0:5000"
alias manpy="python manage.py"

eval $(envkey-source)
