"""create user table

Revision ID: 29460c96b980
Revises:
Create Date: 2018-09-25 13:32:56.681981

"""
from alembic import op
import smpa
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29460c96b980'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', smpa.helpers.database.MyUUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('first_name', sa.Unicode(length=255), nullable=True),
    sa.Column('last_name', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
