FROM quay.io/hactar/python-base:latest AS builder


####################################################################################################
# ENVKEY STUFF
####################################################################################################

# Ensure docker-compose build web is able to pass these env vars in
ARG ENVKEY
ARG SERVER_ENV

# Run envkey-source to get the env vars into the container
COPY ./.staging.env ./.env
RUN eval $(envkey-source)


####################################################################################################
# PROJECT STUFF
####################################################################################################
RUN addgroup -S smpagroup
RUN adduser -S -D -h /usr/app/src smpa smpagroup


ENV PYTHONUNBUFFERED 1
ENV PIPENV_VENV_IN_PROJECT 1
ENV LANG en_GB.utf8

# Create our working directory
RUN mkdir -p /usr/srv/app/

# Poetry install
WORKDIR /usr/srv/app/
COPY ./app/config.toml /usr/srv/app/config.toml
COPY ./app/pyproject.toml /usr/srv/app/pyproject.toml
COPY ./app/poetry.lock /usr/srv/app/poetry.lock
RUN source $HOME/.poetry/env && \
    poetry self:update && \
    poetry install

RUN echo -e "\nalias dev='gunicorn --reload smpa.app -b 0.0.0.0:5000 -t 99999999'\n" >> ~/.zshrc
RUN echo -e "\nalias dev='gunicorn --reload smpa.app -b 0.0.0.0:5000 -t 99999999'\nfunction fish_greeting\n\techo \"🐟 use \`dev\` to run the server\"\n\t echo ""\nend" >> ~/.config/fish/config.fish

ENV SHELL /usr/bin/fish

COPY ./app /usr/srv/app/
COPY ./.staging.env ./.env

# Expose the dev server
EXPOSE 5000

CMD ["python", "wsgi.py"]
# CMD ["sleep", "1000000"]
