site_name: Submit my Planning Application
repo_url: https://code.hactar.is/projects/hackney-planning/repositories/smpa/
repo_name: Codebase
edit_uri: /projects/hackney-planning/repositories/smpa/tree/master/docs/docs
site_dir: build/html
use_directory_urls: true
dev_addr: 127.0.0.1:8008
theme: readthedocs

nav:
- 'index.md'
- 'about.md'
- 'schema.md'
- 'contributing/index.md'
- 'contributing/python.md'
- 'contributing/setup.md'
- Screen notes: 'screens/screens.md'
- API Walkthrough:
  - 'screens/0-screen.md'
  - 'screens/1-screen.md'
  - 'screens/2-screen.md'
  - 'screens/3-screen.md'
  - 'screens/4-screen.md'
  - 'screens/5-screen.md'
  - 'screens/6-screen.md'
  - 'screens/7-screen.md'
  - 'screens/8-screen.md'
  - 'screens/9-screen.md'
  - 'screens/10-screen.md'
  - 'screens/11-screen.md'
  - 'screens/12-screen.md'
  - 'screens/13-screen.md'
  - 'screens/14-screen.md'
  - 'screens/15-screen.md'
  - 'screens/16-screen.md'
  - 'screens/17-screen.md'
  - 'screens/18-screen.md'
  - 'screens/19-screen.md'
  - 'screens/20-screen.md'
  - 'screens/21-screen.md'
  - 'screens/22-screen.md'
  - 'screens/23-screen.md'
  - 'screens/24-screen.md'
  - 'screens/25-screen.md'
  - 'screens/26-screen.md'
  - 'screens/27-screen.md'
  - 'screens/28-screen.md'
  - 'screens/29-screen.md'
  - 'screens/30-screen.md'
  - 'screens/31-screen.md'
  - 'screens/32-screen.md'
  - 'screens/33-screen.md'
  - 'screens/34-screen.md'
  - 'screens/35-screen.md'
  - 'screens/user/user-endpoints.md'
- tests.md
